/**
 * build.js
 * Inlines data.json into index.html so the dashboard is fully self-contained.
 * This allows StaticCrypt to encrypt everything into a single file.
 *
 * Usage: node build.js
 * Output: dist/index.html
 */

const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, 'data.json');
const htmlPath = path.join(__dirname, 'index.html');
const distDir = path.join(__dirname, 'dist');
const outPath = path.join(distDir, 'index.html');

if (!fs.existsSync(dataPath)) {
  console.error('Error: data.json not found. Run fetch-data.js first.');
  process.exit(1);
}

if (!fs.existsSync(distDir)) fs.mkdirSync(distDir);

const data = fs.readFileSync(dataPath, 'utf8');
let html = fs.readFileSync(htmlPath, 'utf8');

// Replace the fetch('data.json') call with inline data
const inlineScript = `
    // Inlined data (generated by build.js)
    const __INLINE_DATA__ = ${data};
    Promise.resolve(__INLINE_DATA__)`;

html = html.replace(
  `fetch('data.json')
      .then(r => { if (!r.ok) throw new Error('data.json not found'); return r.json(); })`,
  inlineScript
);

fs.writeFileSync(outPath, html);
console.log(`✓ dist/index.html written (${(fs.statSync(outPath).size / 1024).toFixed(1)} KB)`);
